"""roles

Revision ID: 71a4ed0f3f1f
Revises: a11f29606de3
Create Date: 2025-03-13 15:42:50.180030

"""
# pylint: disable-all
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "71a4ed0f3f1f"
down_revision: Union[str, None] = "a11f29606de3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "last_updated_by",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("last_updated_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_is_active"), "roles", ["is_active"], unique=False)
    op.create_index(op.f("ix_roles_role"), "roles", ["role"], unique=False)
    op.create_index(op.f("ix_cities_code"), "cities", ["code"], unique=False)
    op.create_index(op.f("ix_cities_is_active"), "cities", ["is_active"], unique=False)
    op.create_index(op.f("ix_cities_name"), "cities", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cities_name"), table_name="cities")
    op.drop_index(op.f("ix_cities_is_active"), table_name="cities")
    op.drop_index(op.f("ix_cities_code"), table_name="cities")
    op.drop_index(op.f("ix_roles_role"), table_name="roles")
    op.drop_index(op.f("ix_roles_is_active"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
