"""sub roles

Revision ID: d1fa0ebd5fa5
Revises: 71a4ed0f3f1f
Create Date: 2025-03-18 10:46:59.127501

"""
# pylint: disable-all
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1fa0ebd5fa5'
down_revision: Union[str, None] = '71a4ed0f3f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subroles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('sub_role_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('sub_role_description', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subroles_id'), 'subroles', ['id'], unique=False)
    op.create_index(op.f('ix_subroles_is_active'), 'subroles', ['is_active'], unique=False)
    op.create_index(op.f('ix_subroles_role_id'), 'subroles', ['role_id'], unique=False)
    op.create_index(op.f('ix_subroles_sub_role_name'), 'subroles', ['sub_role_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subroles_sub_role_name'), table_name='subroles')
    op.drop_index(op.f('ix_subroles_role_id'), table_name='subroles')
    op.drop_index(op.f('ix_subroles_is_active'), table_name='subroles')
    op.drop_index(op.f('ix_subroles_id'), table_name='subroles')
    op.drop_table('subroles')
    # ### end Alembic commands ###
